{ pkgs, ... }:

{
  programs.vscode = {
    enable = true;
    mutableExtensionsDir = false;
    
    # 注意：这一大坨扩展列表
    extensions = with pkgs; [
      vscode-marketplace.akamud.vscode-theme-onedark
      vscode-marketplace.arrterian.nix-env-selector
      vscode-marketplace.arturodent.find-and-transform
      vscode-marketplace.betterthantomorrow.calva
      vscode-marketplace.betterthantomorrow.calva-spritz
      vscode-marketplace.bierner.markdown-mermaid
      vscode-marketplace.bpruitt-goddard.mermaid-markdown-syntax-highlighting
      vscode-marketplace.clinyong.vscode-css-modules
      vscode-marketplace.dlahmad.dracula-for-rust-theme
      vscode-marketplace.docker.docker
      vscode-marketplace.emilast.logfilehighlighter
      vscode-marketplace.eriklynd.json-tools
      vscode-marketplace.esbenp.prettier-vscode
      vscode-marketplace.everettjf.filter-line
      vscode-marketplace.fill-labs.dependi
      vscode-marketplace.golang.go
      vscode-marketplace.ianic.zig-language-extras
      vscode-marketplace.ibm.output-colorizer
      vscode-marketplace.iliazeus.vscode-ansi
      vscode-marketplace.irongeek.vscode-env
      vscode-marketplace.isudox.vscode-jetbrains-keybindings
      vscode-marketplace.jakebecker.elixir-ls
      vscode-marketplace.janisdd.vscode-edit-csv
      vscode-marketplace.jnoortheen.nix-ide
      vscode-marketplace.mads-hartmann.bash-ide-vscode
      vscode-marketplace.marlon407.code-groovy
      vscode-marketplace.mechatroner.rainbow-csv
      vscode-marketplace.mkhl.direnv
      vscode-marketplace.ms-azuretools.vscode-containers
      vscode-marketplace.ms-azuretools.vscode-docker
      vscode-marketplace.ms-python.autopep8
      vscode-marketplace.ms-python.debugpy
      vscode-marketplace.ms-python.isort
      vscode-marketplace.ms-python.python
      vscode-marketplace.ms-python.vscode-pylance
      vscode-marketplace.ms-python.vscode-python-envs
      vscode-marketplace.ms-toolsai.jupyter
      vscode-marketplace.ms-toolsai.jupyter-keymap
      vscode-marketplace.ms-toolsai.jupyter-renderers
      vscode-marketplace.ms-toolsai.vscode-jupyter-cell-tags
      vscode-marketplace.ms-toolsai.vscode-jupyter-slideshow
      vscode-marketplace.ms-vscode-remote.remote-ssh
      vscode-marketplace.ms-vscode-remote.remote-ssh-edit
      vscode-marketplace.ms-vscode.cmake-tools
      vscode-marketplace.ms-vscode.cpptools
      vscode-marketplace.ms-vscode.hexeditor
      vscode-marketplace.ms-vscode.remote-explorer
      vscode-marketplace.ms-vscode.vscode-typescript-next
      vscode-marketplace.naco-siren.gradle-language
      vscode-marketplace.quicktype.quicktype
      vscode-marketplace.randomfractalsinc.geo-data-viewer
      vscode-marketplace.redhat.java
      vscode-marketplace.redhat.vscode-xml
      vscode-marketplace.rust-lang.rust-analyzer
      vscode-marketplace.scala-lang.scala
      vscode-marketplace.scalameta.metals
      vscode-marketplace.shakram02.bash-beautify
      vscode-marketplace.tabbyml.vscode-tabby
      vscode-marketplace.tamasfe.even-better-toml
      vscode-marketplace.tobias-faller.vt100-syntax-highlighting
      vscode-marketplace.twxs.cmake
      vscode-marketplace-universal.vadimcn.vscode-lldb
      vscode-marketplace.vmware.vscode-spring-boot
      vscode-marketplace.vscjava.vscode-gradle
      vscode-marketplace.vscjava.vscode-java-debug
      vscode-marketplace.vscjava.vscode-java-dependency
      vscode-marketplace.vscjava.vscode-java-pack
      vscode-marketplace.vscjava.vscode-java-test
      vscode-marketplace.vscjava.vscode-lombok
      vscode-marketplace.vscjava.vscode-maven
      vscode-marketplace.vscjava.vscode-spring-boot-dashboard
      vscode-marketplace.vscode-icons-team.vscode-icons
      vscode-marketplace.vstirbu.vscode-mermaid-preview
      vscode-marketplace.vue.volar
      vscode-marketplace.wayou.vscode-todo-highlight
      vscode-marketplace.webfreak.debug
      vscode-marketplace.yangdada.vscode-geojsonviewer
      vscode-marketplace.yzhang.markdown-all-in-one
      vscode-marketplace.zainchen.json
      vscode-marketplace.ziglang.vscode-zig
      vscode-marketplace.zxh404.vscode-proto3
      vscode-marketplace.github.github-vscode-theme
    ];
  };
}